import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface Diamond {
  stock: string;
  shape: string;
  weight: number;
  color: string;
  clarity: string;
  price_per_carat: number;
  cut?: string;
  picture?: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { diamonds, buyerName, searchQuery } = await req.json();
    
    if (!diamonds || !Array.isArray(diamonds) || diamonds.length === 0) {
      throw new Error('Invalid diamonds data');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Create diamond list for AI prompt
    const diamondList = diamonds.map((d: Diamond, idx: number) => 
      `${idx + 1}. ${d.shape} ${d.weight}ct - ${d.color} ${d.clarity}${d.cut ? ` (${d.cut})` : ''} - $${(d.price_per_carat * d.weight).toLocaleString()} (Stock: ${d.stock})`
    ).join('\n');

    const totalValue = diamonds.reduce((sum: number, d: Diamond) => 
      sum + (d.price_per_carat * d.weight), 0
    );

    const systemPrompt = `You are a professional diamond dealer assistant. Generate a warm, professional message IN HEBREW to send to a buyer about matched diamonds. The message should be:
- Professional but friendly, written in HEBREW
- Brief and to the point (2-3 sentences max)
- Mention the total number of diamonds and approximate total value
- Express willingness to discuss details
- Use appropriate diamond industry terminology in Hebrew
- DO NOT include greetings or signatures - just the message body
- IMPORTANT: Write ONLY in Hebrew language`;

    const userPrompt = `Generate a message IN HEBREW for buyer "${buyerName || 'לקוח יקר'}" about these ${diamonds.length} matched diamonds:

${diamondList}

Total Value: $${totalValue.toLocaleString()}
${searchQuery ? `Their search: "${searchQuery}"` : ''}

IMPORTANT: Write the entire message in Hebrew. Keep it concise and professional.`;

    console.log('🤖 Generating message with AI...');
    
    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI API error:', response.status, errorText);
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();
    const generatedMessage = data.choices?.[0]?.message?.content;

    if (!generatedMessage) {
      throw new Error('No message generated by AI');
    }

    console.log('✅ Message generated successfully');

    return new Response(
      JSON.stringify({ 
        message: generatedMessage,
        diamonds: diamonds.map((d: Diamond) => ({
          stock: d.stock,
          shape: d.shape,
          weight: d.weight,
          color: d.color,
          clarity: d.clarity,
          price: d.price_per_carat * d.weight,
          picture: d.picture
        })),
        totalValue
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error generating message:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Failed to generate message' 
      }),
      { 
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
