import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface Diamond {
  stock: string;
  shape: string;
  weight: number;
  color: string;
  clarity: string;
  price_per_carat: number;
  cut?: string;
  picture?: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { diamonds, buyerName, searchQuery } = await req.json();
    
    if (!diamonds || !Array.isArray(diamonds) || diamonds.length === 0) {
      throw new Error('Invalid diamonds data');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Create diamond list for AI prompt
    const diamondList = diamonds.map((d: Diamond, idx: number) => {
      const totalPrice = d.price_per_carat * d.weight;
      // If price is negative, it represents a discount percentage
      const priceDisplay = totalPrice < 0 
        ? `הנחה ${Math.abs(totalPrice)}%` 
        : `$${totalPrice.toLocaleString()}`;
      
      return `${idx + 1}. ${d.shape} ${d.weight}ct - ${d.color} ${d.clarity}${d.cut ? ` (${d.cut})` : ''} - ${priceDisplay} (מלאי: ${d.stock})`;
    }).join('\n');

    const totalValue = diamonds.reduce((sum: number, d: Diamond) => {
      const price = d.price_per_carat * d.weight;
      // Skip negative prices (discounts) in total calculation
      return price >= 0 ? sum + price : sum;
    }, 0);

    const systemPrompt = `You are a professional diamond dealer assistant. Generate a warm, helpful message IN HEBREW directly to a buyer about diamonds that match their search. The message should be:
- Warm and customer-focused, written in HEBREW
- Address the buyer directly (use "שלום" or mention their name)
- Brief (2-3 sentences max)
- Mention what you found for them based on their search
- Invite them to view details and contact for more information
- Use friendly, professional tone in Hebrew
- DO NOT include seller perspective or "I'm sending you" - speak directly to the buyer
- IMPORTANT: Write ONLY in Hebrew language`;

    const userPrompt = `Generate a message IN HEBREW directly to buyer "${buyerName || 'לקוח יקר'}" about ${diamonds.length} diamonds you found for them:

${diamondList}

${searchQuery ? `They searched for: "${searchQuery}"` : 'Based on their preferences'}

IMPORTANT: Write directly to the buyer in Hebrew. Make them feel you found something special for them.`;

    console.log('🤖 Generating message with AI...');
    
    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI API error:', response.status, errorText);
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();
    const generatedMessage = data.choices?.[0]?.message?.content;

    if (!generatedMessage) {
      throw new Error('No message generated by AI');
    }

    console.log('✅ Message generated successfully');

    return new Response(
      JSON.stringify({ 
        message: generatedMessage,
        diamonds: diamonds.map((d: Diamond) => {
          const totalPrice = d.price_per_carat * d.weight;
          return {
            stock: d.stock,
            shape: d.shape,
            weight: d.weight,
            color: d.color,
            clarity: d.clarity,
            price: totalPrice,
            picture: d.picture
          };
        }),
        totalValue
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error generating message:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Failed to generate message' 
      }),
      { 
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
