import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { buyer_name, diamonds, search_query, tone = 'professional' } = await req.json();

    if (!diamonds || !Array.isArray(diamonds) || diamonds.length === 0) {
      throw new Error('No diamonds provided');
    }

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    console.log('🤖 Generating AI response for:', buyer_name);

    // Calculate total value
    const totalValue = diamonds.reduce((sum, d) => {
      const price = d.price_per_carat ? d.price_per_carat * d.weight : d.price || 0;
      return sum + price;
    }, 0);

    // Create diamond list with details
    const diamondList = diamonds.map((d, idx) => {
      const price = d.price_per_carat ? d.price_per_carat * d.weight : d.price || 0;
      return `${idx + 1}. ${d.shape} ${d.weight}ct - ${d.color} ${d.clarity}${d.cut ? ` (${d.cut})` : ''} - $${price.toLocaleString()} (Stock: ${d.stock_number || d.stock})`;
    }).join('\n');

    // Dynamic system prompt based on tone
    const tonePrompts = {
      professional: 'You are a professional diamond dealer. Generate a concise, business-like message.',
      friendly: 'You are a friendly diamond consultant. Generate a warm, personalized message.',
      brief: 'You are a direct diamond dealer. Generate a very brief, to-the-point message (1-2 sentences max).'
    };

    const systemPrompt = `${tonePrompts[tone as keyof typeof tonePrompts] || tonePrompts.professional}

Rules:
- Write in Hebrew (עברית)
- Keep it professional but warm
- Mention the number of matched diamonds
- Include the total value
- Express willingness to discuss
- NO greetings or signatures - just the message body
- 2-3 sentences maximum`;

    const userPrompt = `Generate a message for buyer "${buyer_name || 'לקוח יקר'}" about these ${diamonds.length} matched diamonds:

${diamondList}

Total Value: $${totalValue.toLocaleString()}
${search_query ? `Their search: "${search_query}"` : ''}

Keep it concise, professional, and in Hebrew.`;

    // Call Lovable AI
    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('❌ AI API error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 429) {
        throw new Error('RATE_LIMIT: Too many requests. Please try again in a moment.');
      } else if (aiResponse.status === 402) {
        throw new Error('PAYMENT_REQUIRED: AI credits exhausted. Please add credits.');
      }
      
      throw new Error(`AI API error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const generatedMessage = aiData.choices?.[0]?.message?.content;

    if (!generatedMessage) {
      throw new Error('No message generated by AI');
    }

    console.log('✅ AI response generated successfully');

    // Format diamonds for response
    const formattedDiamonds = diamonds.map(d => {
      const price = d.price_per_carat ? d.price_per_carat * d.weight : d.price || 0;
      return {
        stock: d.stock_number || d.stock,
        shape: d.shape,
        weight: d.weight,
        color: d.color,
        clarity: d.clarity,
        cut: d.cut,
        price: price,
        picture: d.picture || d.image_url
      };
    });

    return new Response(
      JSON.stringify({ 
        message: generatedMessage,
        diamonds: formattedDiamonds,
        totalValue,
        tone
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('❌ Error generating AI response:', error);
    
    const errorMessage = error instanceof Error ? error.message : 'Failed to generate response';
    const isRateLimit = errorMessage.includes('RATE_LIMIT');
    const isPaymentRequired = errorMessage.includes('PAYMENT_REQUIRED');
    
    return new Response(
      JSON.stringify({ 
        error: errorMessage,
        error_code: isRateLimit ? 'RATE_LIMIT' : isPaymentRequired ? 'PAYMENT_REQUIRED' : 'UNKNOWN'
      }),
      { 
        status: isRateLimit ? 429 : isPaymentRequired ? 402 : 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
