import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { corsHeaders } from '../_shared/cors.ts';

const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');

interface DiamondData {
  shape: string;
  weight: number;
  color: string;
  clarity: string;
  cut: string;
  stock_number: string;
  price_per_carat?: number;
}

interface GenerateMessageRequest {
  diamond: DiamondData;
  start_price: number;
  min_increment: number;
  hours_remaining: number;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { diamond, start_price, min_increment, hours_remaining }: GenerateMessageRequest = await req.json();

    console.log('🤖 Generating auction message for:', diamond.stock_number);

    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Build prompt for AI
    const prompt = `כתוב הודעת מכירה פומבית מקצועית בעברית ליהלום עם הפרטים הבאים:
- צורה: ${diamond.shape}
- משקל: ${diamond.weight} קראט
- צבע: ${diamond.color}
- ניקיון: ${diamond.clarity}
- חיתוך: ${diamond.cut}
- מספר מלאי: ${diamond.stock_number}

מחיר פתיחה: $${start_price.toLocaleString()}
הפרש מינימלי להצעה: $${min_increment}
זמן נותר: ${hours_remaining} שעות

ההודעה צריכה להיות:
1. קצרה ומרשימה (2-3 שורות בלבד)
2. כוללת אמוג'י רלוונטיים
3. יוצרת דחיפות ועניין
4. פרופסיונלית אך מזמינה

דוגמה לסגנון: "🔨 מכרז פעיל - יהלום יוקרתי! 💎 1.50ct ROUND BRILLIANT | G צבע • VS1 ניקיון • Excellent חיתוך | מחיר פתיחה: $5,000 | הצעה הבאה: +$100 | ⏰ נגמר בעוד 24 שעות"`;

    // Call Lovable AI Gateway with gemini-2.5-flash
    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: 'אתה מומחה לשיווק יהלומים בעברית. תכתוב הודעות מכירה פומבית קצרות, מרשימות ויעילות.' },
          { role: 'user', content: prompt }
        ],
        max_tokens: 200,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI Gateway error:', response.status, errorText);
      
      // Fallback to template if AI fails
      const fallbackMessage = `🔨 מכרז פעיל - יהלום יוקרתי!

💎 ${diamond.weight}ct ${diamond.shape}
🎨 ${diamond.color} צבע • ${diamond.clarity} ניקיון • ${diamond.cut} חיתוך

💰 מחיר פתיחה: $${start_price.toLocaleString()}
📈 הצעה הבאה: +$${min_increment}
⏰ נגמר בעוד: ${hours_remaining} שעות

✨ אל תפספסו את ההזדמנות!`;

      return new Response(
        JSON.stringify({ 
          success: true, 
          message: fallbackMessage,
          used_fallback: true 
        }),
        { 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 200 
        }
      );
    }

    const data = await response.json();
    const aiMessage = data.choices?.[0]?.message?.content;

    if (!aiMessage) {
      throw new Error('No message generated by AI');
    }

    console.log('✅ AI message generated successfully');

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: aiMessage.trim(),
        used_fallback: false 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );
  } catch (error) {
    console.error('❌ Error generating auction message:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Failed to generate message' 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
